name: 'test'
description: 'Perform a testrun'
inputs:
    repo:
      description: 'PscyhoJS Repository'
      required: true
    ref:
      description: 'Branch/tag/SHA (default branch if empty)'
      required: false
      default: ''
    testrun:
      description: 'testrun'
      required: true
    subset:
      description: 'subset'
      required: true
    platform:
      description: 'platform'
      required: true
    label:
      description: 'label'
      required: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          
      # START: install psychojs_testing
      - name: Checkout psychojs_testing
        uses: actions/checkout@v2
        with:
          repository: psychopy/psychojs_testing
          path: psychojs_testing
      - name: Cache modules psychojs_testing
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs_testing
        with:
          path: ~/psychojs_testing/.npmrepo
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs_testing
        run: npm --prefix psychojs_testing ci
      # END: install psychojs_testing
    
      # START: install psychojs
      - name: Checkout psychojs
        uses: actions/checkout@v2
        with:
          repository: ${{env.INPUT_REPO}}
          ref: ${{env.INPUT_REF}}
          path: psychojs
      - name: Cache modules psychojs
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs
        with:
          path: ~/psychojs/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs
        run: npm --prefix psychojs ci
      # END: install psychojs
      
      # START: wait for other workflows to complete
      - name: Turnstyle (wait for other workflows to complete)
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # END: wait for other workflows to complete          
      
      # START: run tests
      - name: Run test
        run: node test.cjs --server bs --testrun ${{env.INPUT_TESTRUN}} --subset ${{github.event.inputs.subset}} --platform ${{env.INPUT_PLATFORM}} --url stager --uploadExperiments --uploadResults --label ${{env.INPUT_LABEL}}
        working-directory: ./psychojs_testing        
      # END: run tests
