name: compile psyexp to js
on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: sh
    env:
      STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
      STAGING_PORT: ${{ secrets.STAGING_PORT }}
      STAGING_USERNAME: ${{ secrets.STAGING_USERNAME }}
      PSYCHOPY_PATH: '../psychopy'
      PYTHON_VERSION: '3.8'
      PYGLET: '1.3'
      DISPLAY: ':99.0'
    steps:
      - name: Checkout PsychoJS
        uses: actions/checkout@v2
        with:
          path: psychojs
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache PsychoJS node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/psychojs/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install PsychoJS node modules
        run: npm ci
        working-directory: ./psychojs
      - name: Checkout PsychoPy
        uses: actions/checkout@v2
        with:
          repository: psychopy/psychopy
          path: psychopy
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        name: Cache PsychoPy dependencies
        with:
          path: ~/psychopy/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install PsychoPy dependencies
        run: pip install -e .
        working-directory: ./psychopy
      - name: Install wxPython
        run: pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython
        working-directory: ./psychopy
      - name: Update APT
        run: sudo apt update
      - name: Install wxPython dependencies
        run: sudo apt-get install git curl libsdl2-mixer-2.0-0 libsdl2-image-2.0-0 libsdl2-2.0-0
      - name: Install Travis dependencies
        run: pip install -r requirements_travis.txt
        working-directory: ./psychopy
      - name: Activate virtual screen
        run: /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1024x768x24 -ac +extension GLX +extension RANDR +render -noreset
      - name: Compile experiments from psyexp to JS
        run: node test/cli/compileExperiments.js
        working-directory: ./psychojs
