name: e2e test all_devices
on:
  schedule:
    - cron: '5 8 * * sun'
  workflow_dispatch:

env:
  BROWSERSTACK_ACCESSKEY: ${{ secrets.BROWSERSTACK_ACCESSKEY }}
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
  STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
  STAGING_PORT: ${{ secrets.STAGING_PORT }}
  STAGING_USERNAME: ${{ secrets.STAGING_USERNAME }}
  PSYCHOJS_PATH: '/home/runner/work/e2e_robot/e2e_robot/psychojs'

jobs:
  prepare:
    name: Clean up and get tests
    runs-on: ubuntu-latest
    outputs:
      tests: ${{steps.get_tests.outputs.tests}} 
    steps:
      # START: install psychojs_tests
      - name: Checkout psychojs_tests
        uses: actions/checkout@v2
        with:
          repository: tpronk/e2e_robot
          path: psychojs_tests
      - name: Cache modules psychojs_tests
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs_tests
        with:
          path: ~/psychojs_tests/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs_tests
        run: npm --prefix psychojs_tests ci
      # END: install psychojs_tests
      
      - name: Turnstyle (wait for other workflows to complete)
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Sync BS logs and Stager with GitHub 
        run: node scripts/cli/syncWithGitHub.cjs alain sotiri thomas
        working-directory: ./psychojs_tests        
      - name: Delete old test logs 
        run: node scripts/cli/deleteLogs.cjs --testrun all_devices
        working-directory: ./psychojs_tests        
      - name: Get tests
        id: get_tests
        run: echo "::set-output name=tests::$(node scripts/cli/tabulateTests.cjs --label all --outputFormat paths)"
        working-directory: ./psychojs_tests        

  tests:
    name: Test 
    needs: [prepare]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix: 
        test: ${{fromJson(needs.prepare.outputs.tests)}}
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          
      # START: install psychojs_tests
      - name: Checkout psychojs_tests
        uses: actions/checkout@v2
        with:
          repository: tpronk/e2e_robot
          path: psychojs_tests
      - name: Cache modules psychojs_tests
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs_tests
        with:
          path: ~/psychojs_tests/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs_tests
        run: npm --prefix psychojs_tests ci
      # END: install psychojs_tests
    
      # START: install psychojs
      - name: Checkout psychojs
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repo || 'tpronk/psychojs' }}
          ref: ${{ github.event.inputs.ref }}
          path: psychojs
      - name: Cache modules psychojs
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs
        with:
          path: ~/psychojs/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs
        run: npm --prefix psychojs ci
      # END: install psychojs
      
      # START: wait for other workflows to complete
      - name: Turnstyle (wait for other workflows to complete)
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # END: wait for other workflows to complete          
      
      # START: run tests
      - name: Run e2e_test selected_devices
        run: node test.cjs --server bs --testrun all_devices --url stager --platform *Windows*Chrome* --uploadExperiments --uploadResults --label ${{ matrix.test }}
        working-directory: ./psychojs_tests        
      # END: run tests

  join_reports:
    name: Join reports
    needs: [tests]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # START: install psychojs_tests
      - name: Checkout psychojs_tests
        uses: actions/checkout@v2
        with:
          repository: tpronk/e2e_robot
          path: psychojs_tests
      - name: Cache modules psychojs_tests
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs_tests
        with:
          path: ~/psychojs_tests/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs_tests
        run: npm --prefix psychojs_tests ci
      # END: install psychojs_tests
      
      - name: Turnstyle (wait for other workflows to complete)
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Join reports
        run: node scripts/cli/joinReports.cjs --testrun all_devices
        working-directory: ./psychojs_tests   
