name: test external pull request
on: 
  pull_request_target:
    types: [assigned, unassigned, labeled, opened, edited, closed, reopened, synchronize, ready_for_review, locked, unlocked, review_requested, review_request_removed]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DUMMY_SECRET: ${{ secrets.DUMMY_SECRET }}
    steps:
      - name: echo pull_request_target type
        run: echo ${{ github.event.type }}
