# Starts up a separate BrowserStack session for each combination of platform and test. That's relatively slow, but also thorough,
# since a failed test does not abort any successive tests. By default, the tests matching label "all" are run on all included platfoms.
name: test_thorough
env:
  DEFAULT_REPO: 'tpronk/psychojs'
  DEFAULT_REF: ''
  DEFAULT_TESTRUN: 'test_thorough'
  DEFAULT_SUBSET: 'false'
  DEFAULT_PLATFORM: '\*'
  DEFAULT_LABEL: 'all'
on:
  schedule:
    - cron: '0 8 * * sun'
  workflow_dispatch:
    inputs:
      repo:
        description: 'PscyhoJS Repository'
        required: true
        default: 'tpronk/psychojs'
      ref:
        description: 'Branch/tag/SHA (default branch if empty)'
        required: false
        default: ''
      testrun:
        description: 'testrun'
        required: true
        default: ${{env.DEFAULT_TESTRUN}}
      subset:
        description: 'subset'
        required: true
        default: 'false'
      platform:
        description: 'platform'
        required: true
        default: '\*'
      label:
        description: 'label'
        required: true
        default: 'all'        
env:
  BROWSERSTACK_ACCESSKEY: ${{ secrets.BROWSERSTACK_ACCESSKEY }}
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
  STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
  STAGING_PORT: ${{ secrets.STAGING_PORT }}
  STAGING_USERNAME: ${{ secrets.STAGING_USERNAME }}
  PSYCHOJS_PATH: '/home/runner/work/psychojs_testing/psychojs_testing/psychojs'

jobs:
  prepare:
    name: Clean up and get tests
    runs-on: ubuntu-latest
    outputs:
      tests: ${{steps.get_tests.outputs.tests}} 
    steps:
      # START: install psychojs_testing
      - name: Checkout psychojs_testing
        uses: actions/checkout@v2
        with:
          repository: psychopy/psychojs_testing
          path: psychojs_testing
      - name: Cache modules psychojs_testing
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs_testing
        with:
          path: ~/psychojs_testing/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs_testing
        run: npm --prefix psychojs_testing ci
      # END: install psychojs_testing
      
      - name: Turnstyle (wait for other workflows to complete)
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Sync BS logs and Stager with GitHub 
        run: node scripts/cli/syncWithGitHub.cjs alain sotiri thomas
        working-directory: ./psychojs_testing
      - name: Delete old test logs 
        run: node scripts/cli/deleteLogs.cjs --testrun ${{github.event.inputs.testrun}}
        working-directory: ./psychojs_testing
      - name: Get tests
        id: get_tests
        run: echo "::set-output name=tests::$(node scripts/cli/tabulateTests.cjs --label ${{github.event.inputs.label}} --outputFormat paths)"
        working-directory: ./psychojs_testing

  tests:
    name: Test 
    needs: [prepare]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      max-parallel: 1
      matrix: 
        test: ${{fromJson(needs.prepare.outputs.tests)}}
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
          
      # START: install psychojs_testing
      - name: Checkout psychojs_testing
        uses: actions/checkout@v2
        with:
          repository: psychopy/psychojs_testing
          path: psychojs_testing
      - name: Cache modules psychojs_testing
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs_testing
        with:
          path: ~/psychojs_testing/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs_testing
        run: npm --prefix psychojs_testing ci
      # END: install psychojs_testing
    
      # START: install psychojs
      - name: Checkout psychojs
        uses: actions/checkout@v2
        with:
          repository: ${{github.event.inputs.repo}}
          ref: ${{github.event.inputs.ref}}
          path: psychojs
      - name: Cache modules psychojs
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs
        with:
          path: ~/psychojs/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs
        run: npm --prefix psychojs ci
      # END: install psychojs
      
      # START: wait for other workflows to complete
      - name: Turnstyle (wait for other workflows to complete)
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # END: wait for other workflows to complete          
      
      # START: run tests
      - name: Run test
        run: node test.cjs --server bs --testrun ${{github.event.inputs.testrun}} --subset ${{github.event.inputs.subset}} --platform ${{github.event.inputs.platform}} --url stager --uploadExperiments --uploadResults --label ${{matrix.test}}
        working-directory: ./psychojs_testing        
      # END: run tests

  join_reports:
    name: Join reports
    needs: [tests]
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      # START: install psychojs_testing
      - name: Checkout psychojs_testing
        uses: actions/checkout@v2
        with:
          repository: psychopy/psychojs_testing
          path: psychojs_testing
      - name: Cache modules psychojs_testing
        uses: actions/cache@v2
        env:
          cache-name: cache-modules-psychojs_testing
        with:
          path: ~/psychojs_testing/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install psychojs_testing
        run: npm --prefix psychojs_testing ci
      # END: install psychojs_testing
      
      - name: Turnstyle (wait for other workflows to complete)
        uses: softprops/turnstyle@v1
        with:
          poll-interval-seconds: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Join reports
        run: node scripts/cli/joinReports.cjs --testrun ${{github.event.inputs.testrun}} 
        working-directory: ./psychojs_testing   
