name: test external pull request
on:


jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BROWSERSTACK_ACCESSKEY: ${{ secrets.BROWSERSTACK_ACCESSKEY }}
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
      STAGING_PORT: ${{ secrets.STAGING_PORT }}
      STAGING_USERNAME: ${{ secrets.STAGING_USERNAME }}
    steps:
