name: Test variables
on:
  workflow_dispatch:

env:
  BROWSERSTACK_ACCESSKEY: ${{ secrets.BROWSERSTACK_ACCESSKEY }}
  BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
  STAGING_PASSWORD: ${{ secrets.STAGING_PASSWORD }}
  STAGING_PORT: ${{ secrets.STAGING_PORT }}
  STAGING_USERNAME: ${{ secrets.STAGING_USERNAME }}

jobs:
  sync_with_github:
    name: Test variables
    runs-on: ubuntu-latest
    outputs: 
      TESTS: ${{env.TESTS}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-:  
      - name: Install modules
        run: npm ci
      - name: Set the value
        id: step_one
        run: echo "TESTS=$(node test/cli/printTests.cjs)" >> $GITHUB_ENV
      - name: Echo the value
        run: echo ${{env.TESTS}}
  e2e_tests:
    name: Run e2e tests
    needs: [sync_with_github]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix: 
        test: ${{fromJson(needs.sync_with_github.outputs.TESTS)}}
    steps:
      - name: Echo all tests
        run: echo ${{needs.sync_with_github.outputs.TESTS}}
      - name: Echo ${{ matrix.test }}
        run: echo ${{ matrix.test }}
      
